@startuml sokoban
left to right direction
skinparam packageStyle rectangle
actor Jugador
(Iniciar partida) as iniciar
(Mover jugador) as moverj
(Cargar un nivel) as cargar

Jugador -- iniciar
Jugador -- moverj
Jugador -- (Reiniciar partida)
Jugador -- (Terminar partida)

iniciar .> cargar : include
moverj <. cargar : extend
(Reiniciar partida) -down.> cargar : include

moverj <. (Mover caja) : extend
@enduml